repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
        exclude: ^(.github/ISSUE_TEMPLATE/config.yml)
    -   id: check-toml
    -   id: pretty-format-json