name = "کیتا"
description = "یک تم تمیز و ساده برای بلاگ Zola"
license = "MIT"
homepage = "https://github.com/Thecode764/kita"
min_version = "0.17.0"
demo = "https://st1020.github.io/kita/"

[author]
name = "آرتین کریمی"
homepage = "https://thecode764.github.io"

[original]
author = "st1020"
homepage = "https://st1020.com"
repo = "https://github.com/st1020/kita"
