blank_issues_enabled: true
contact_links:
  - name: Website
    url: https://thecode764.github.io/Kita-website
    about: Official kita website
  - name: Docs
     url: https://thecode764.github.io/kita-docs
     about: Official kita docs
  - name: Official blog
     url: https://thecode764.github.io/kita
     about: Official blog
  - name: Status
     url: https://thecode764.github.io/status
     about: Kita status