[[post]]
image = "https://thecode764.github.io/kita/icons8-new-100.png"
description = "بخش پست راه اندازی شد! مدتی بود که در فکر این بودیم سیستم گذاشتن پست را برای کیتا فعال کنیم. و در آخر هم این اتفاق افتاد"
