<?php

return [

    /**
     
     * Array of icon definitions where the array key is the file extension
     * (without a preceding dot) and the array value is the desired Font Awesome
     * class names.
     
     */
    'icons' => [
        'apk' => 'fab fa-android',
        'app' => 'fas fa-window',
        'avi' => 'fas fa-video',
        'bak' => 'fas fa-save',
        'bat' => 'fas fa-terminal',
        'box' => 'fas fa-archive',
        'c' => 'fas fa-code',
        'cfg' => 'fas fa-file-alt',
        'class' => 'fas fa-code',
        'cmd' => 'fas fa-terminal',
        'com' => 'fas fa-window',
        'cpp' => 'fas fa-code',
        'css' => 'fab fab fa-css3',
        'csv' => 'fas fa-file-csv',
        'deb' => 'fas fa-archive',
        'doc' => 'fas fa-file-word',
        'docx' => 'fas fa-file-word',
        'email' => 'fas fa-envelope',
        'eot' => 'fas fa-font-case',
        'erb' => 'fas fa-code',
        'exe' => 'fab fa-windows',
        'flv' => 'fas fa-video',
        'gam' => 'fas fa-gamepad',
        'htm' => 'fab fa-html5',
        'html' => 'fab fa-html5',
        'ini' => 'fas fa-file-alt',
        'iso' => 'fas fa-compact-disc',
        'jar' => 'fas fa-window',
        'java' => 'fab fa-java',
        'js' => 'fab fa-js',
        'json' => 'fas fa-file-alt',
        'lock' => 'fas fa-lock',
        'log' => 'fas fa-file-alt',
        'mail' => 'fas fa-envelope',
        'md' => 'fab fa-markdown',
        'mkv' => 'fas fa-video',
        'mov' => 'fas fa-video',
        'mp4' => 'fas fa-video',
        'mpg' => 'fas fa-video',
        'msg' => 'fas fa-envelope',
        'msi' => 'fas fa-window',
        'nes' => 'fas fa-gamepad',
        'odt' => 'fas fa-file-alt',
        'ogv' => 'fas fa-video',
        'otf' => 'fas fa-font-case',
        'pdf' => 'fas fa-file-pdf',
        'php' => 'fab fa-php',
        'phtml' => 'fab fa-html5',
        'pl' => 'fas fa-code',
        'ppt' => 'fas fa-file-powerpoint',
        'pptx' => 'fas fa-file-powerpoint',
        'py' => 'fab fa-python',
        'rb' => 'fas fa-code',
        'rom' => 'fas fa-gamepad',
        'rpm' => 'fas fa-archive',
        'rtf' => 'fas fa-file-alt',
        'sav' => 'fas fa-save',
        'sh' => 'fas fa-terminal',
        'swf' => 'fas fa-video',
        'ttf' => 'fas fa-font-case',
        'twig' => 'fab fa-php',
        'txt' => 'fas fa-file-alt',
        'vb' => 'fas fa-window',
        'webm' => 'fas fa-video',
        'wmv' => 'fas fa-video',
        'woff' => 'fas fa-font-case',
        'xhtml' => 'fas fa-code',
        'xls' => 'fas fa-file-excel',
        'xlsx' => 'fas fa-file-excel',
        'xml' => 'fas fa-code',
        'yaml' => 'fas fa-file-alt',
        'zip' => 'fas fa-file-archive',
    ],
];


