name: Post to Mastodon

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  post_to_mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send toot to Mastodon
        id: mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_TOKEN }} # access token
          url: ${{ secrets.MASTODON_URL }} # Mastodon instance URL
          message: "Hello from GitHub Actions!"
          visibility: "public" 
