name: Update with files and directories
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs: 
    update-files-and-directories: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Remove the file
              run: rm -f FILES-AND-DIRECTORIES.md
            - name: Write the file
              run: |
                echo "```" > FILES-AND-DIRECTORIES.md tree >> FILES-AND-DIRECTORIES.md echo "

            - name: Set file permissions
              run: chmod 644 FILES-AND-DIRECTORIES.md
            - name: Push
              run: |
                   git config --global user.name "Github actions"
                   git config --global user.email "actions@github.com"
                   git add.
                   git commit -m "📝 Update files and directories"
                   git push
