name: Update project directories and files
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs: 
    update-base: 
        name: Update the project directories and files base file
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Remove the BASE.md file
              run: rm BASE.md
            - name: Create again the BASE.md file
              run: touch BASE.md
            - name: Update with files and directories
              run: echo ($eval cat) >> BASE.md
            - name: Login to github action
              run: git config --global user.name "Github actions"
            - name: Email for github actions account
              run: git config --global user.email "actions@github.com"
            - name: Add files to git
              run: git add .
            - name: Commit files
              run: git commit -m "📝 Update files and directories"
            - name: Push!
              run: git push
